language: python

python:
  - "3.6"

install:
  - pip install pygcn, numpy, scipy, astropy, healpy
  - pip install requests, pyyaml, loguru
  - pip install codecov

script:
  - coverage run --source=torosgcn setup.py test

after_success:
  - codecov
